parameters:   
  - name: Comment
    displayName: Comment - included in build number
    default: '-'
    type: string

  - name: Deploy
    displayName: Deploy changes to tenant - if unchecked, only performs a preview and will not make any changes to the tenant
    default: true
    type: boolean

  - name: UseLastDeployTagForExport
    displayName: Gets the state of the last deployment, before doing an export - if unchecked, will use latest state of repo
    default: true
    type: boolean

  - name: Export
    displayName: Run an export operation before running the deployment - this is recommended to prevent any unintentional loss of changes made manually to the tenant
    default: true
    type: boolean
    
  - name: UpdateBaseline
    displayName: Update to use the latest baseline during the deployment - if unchecked, the deployment will use the same version of the baseline as used for the last successful deployment
    default: true
    type: boolean

name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none

schedules:
- cron: "0 7 * * *"
  displayName: Daily Run 7AM UTC
  branches:
    include:
    - master
  always: true

pool:
  vmImage: windows-latest

resources:
  repositories:
  - repository: Templates
    type: github
    name: simeoncloud/AzurePipelineTemplates
    ref: refs/heads/feature/sync
    endpoint: simeoncloud

stages:
- template: Sync.yml@Templates
  parameters:
    Comment: ${{ parameters.Comment }}
    Deploy: ${{ parameters.Deploy }}
    UseLastDeployTagForExport: ${{ parameters.UseLastDeployTagForExport }}
    Export: ${{ parameters.Export }}
    UpdateBaseline: ${{ parameters.UpdateBaseline }}
